// Generated by CoffeeScript 1.4.0
(function() {
  var Object;

  Object = require('../models/object');

  exports.html_preview = function(req, res) {
    var id,
      _this = this;
    id = req.params.id;
    return Object.model.findById(id, function(err, item) {
      var html;
      html = item.data.html;
      return res.render('layout', {
        content: html
      });
    });
  };

  exports.html_edit = function(req, res) {
    return res.render('html_edit');
  };

  exports.text_view = function(req, res) {
    var id,
      _this = this;
    id = req.params.id;
    return Object.model.findById(id, function(err, item) {
      res.writeHead(200);
      res.write(item.data.text);
      return res.end();
    });
  };

  exports.graphics_view = function(req, res) {
    return res.end();
  };

  exports.graph_view = function(req, res) {
    return res.end();
  };

  exports.calendar_view = function(req, res) {
    return res.end();
  };

  exports.grid_view = function(req, res) {
    return res.end();
  };

  exports.board_view = function(req, res) {
    return res.end();
  };

  exports.mobile_view = function(req, res) {
    return res.end();
  };

  exports.backbone_editor = function(req, res) {
    return res.end();
  };

}).call(this);
