// Generated by CoffeeScript 1.4.0
(function() {
  var Object;

  Object = require('../models/object');

  exports.mongoose2backbone = function(model) {
    return {
      id: model._id,
      data: model.data,
      links: model.links
    };
  };

  exports.init = function(req, res) {
    var newObj,
      _this = this;
    newObj = new Object.model();
    newObj.data = {
      html: "hello",
      text: "demo"
    };
    newObj.links = [];
    return newObj.save(function(err) {
      return res.json({
        id: newObj._id
      });
    });
  };

  exports.get_all = function(req, res) {
    var _this = this;
    return Object.model.find({}, function(err, items) {
      var i, result, _i, _len;
      result = [];
      for (_i = 0, _len = items.length; _i < _len; _i++) {
        i = items[_i];
        result.push(exports.mongoose2backbone(i));
      }
      return res.json(result);
    });
  };

  exports.get_one = function(req, res) {
    var _this = this;
    return Object.model.findById(req.params.id, function(err, item) {
      return res.json(exports.mongoose2backbone(item));
    });
  };

  exports.add_new = function(req, res) {
    var newObj;
    newObj = new Object.model();
    newObj.data = req.data;
    newObj.links = req.links;
    return newObj.save(function(err) {
      var result;
      result = {
        id: newObj._id
      };
      return res.json(result);
    });
  };

  exports.update = function(req, res) {
    var result;
    result = {};
    return Object.model.update(req.body, function(err) {
      return res.json(result);
    });
  };

  exports.remove = function(req, res) {
    var result;
    result = {};
    return Object.model.remove(req.body, function(err) {
      return res.json(result);
    });
  };

}).call(this);
