// Generated by CoffeeScript 1.4.0
(function() {
  var Object, fs;

  Object = require('../models/object');

  fs = require('fs');

  exports.upload_form = function(req, res) {
    return res.render("upload");
  };

  exports.add_new = function(req, res) {
    var obj;
    console.log("Receive: ", req.files.path);
    obj = new Object.model();
    obj.data = {
      path: req.files.file.path
    };
    return obj.save(function(err) {
      return res.json({
        id: obj.id
      });
    });
  };

  exports.get_one = function(req, res) {
    var _this = this;
    return Object.model.findById(req.params.id, function(err, item) {
      console.log(item.get_path);
      if (item.get_path !== null) {
        return res.sendfile(item.get_path);
      } else {
        return res.json({
          code: 1,
          message: "Resources not found."
        });
      }
    });
  };

}).call(this);
